version: '3.8'

services:
  django:
    build: .
    container_name: mentorat_site
    expose:
      - "8000"
    environment:
      DJANGO_SETTINGS_MODULE: website.settings
      DATABASE_NAME: mentors_db
      DATABASE_USER: mentors_user
      DATABASE_PASSWORD: your_secure_password
      DATABASE_HOST: 188.8.9.23
      DATABASE_PORT: 5432
    volumes:
      - .:/var/www/site
      - static_volume:/var/www/site/static

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/var/www/site/static
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    entrypoint: "/bin/sh -c"
    command: > 
      "certbot certonly --webroot 
      --webroot-path=/var/www/site/static 
      --email infos@oser-bf.org 
      --agree-tos 
      --no-eff-email 
      -d oser-bf.org"

volumes:
  static_volume:
  certbot-etc:
  certbot-var:
