# Generated by Django 5.0.2 on 2024-07-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mot_du_Fondateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.TextField(blank=True, null=True, verbose_name='Mot du fondateur')),
                ('statut', models.CharField(blank=True, choices=[('actif', 'mot actif'), ('inactif', 'mot inactif')], max_length=32, null=True, verbose_name='Statut')),
            ],
        ),
    ]
