# Generated by Django 5.0.2 on 2024-10-30 17:28

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateField(auto_created=True, auto_now=True, null=True)),
                ('created', models.DateField(auto_created=True, auto_now_add=True, null=True)),
                ('objet', models.CharField(max_length=200)),
                ('contenu', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Contenu')),
            ],
        ),
    ]
