# Generated by Django 5.0.2 on 2024-03-04 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='etablissement',
        ),
        migrations.AddField(
            model_name='etablissement',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentors.communes'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentors.status'),
        ),
    ]
