# Generated by Django 5.0.2 on 2024-06-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='about1',
            field=models.TextField(blank=True, null=True, verbose_name='A propos de 2click'),
        ),
    ]
