# Generated by Django 5.0.2 on 2024-10-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailspersonnalisee',
            name='intituler',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mailspersonnalisee',
            name='objet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
