# Generated by Django 5.0.2 on 2024-10-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_alter_mailspersonnalisee_intituler_and_more'),
        ('mentors', '0002_emailing'),
    ]

    operations = [
    ]
