# Generated by Django 5.0.2 on 2024-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mailspersonnalisee_delete_mailpersonalise'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailspersonnalisee',
            name='objet',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
