# Generated by Django 5.0.2 on 2024-03-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_remove_etablissement_etablissement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
