# Generated by Django 5.0.2 on 2024-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_activite'),
    ]

    operations = [
        migrations.AddField(
            model_name='politique_securite',
            name='date_even',
            field=models.DateField(blank=True, null=True, verbose_name="Date de l'activité"),
        ),
    ]
