# Generated by Django 5.0.2 on 2024-08-11 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_delete_mailpersonalise_mailspersonnalisee_objet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mentore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='profiles',
            name='can_be_mentor',
            field=models.BooleanField(default=False, verbose_name='Peut etre mentor?'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='profile',
            field=models.ForeignKey(limit_choices_to={'can_be_mentor': True}, on_delete=django.db.models.deletion.CASCADE, to='mentors.profiles'),
        ),
        migrations.AddField(
            model_name='mentore',
            name='profile',
            field=models.ForeignKey(limit_choices_to={'can_be_mentor': False}, on_delete=django.db.models.deletion.CASCADE, to='mentors.profiles'),
        ),
    ]
