# Generated by Django 5.0.2 on 2024-03-05 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_profiles_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_profiles', to='mentors.profiles'),
        ),
    ]
