# Generated by Django 5.0.2 on 2025-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_merge_20241030_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='bourse_opportinute',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailspersonnalisee',
            name='intituler',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mailspersonnalisee',
            name='objet',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
