# Generated by Django 5.0.2 on 2024-06-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_politique_securite_date_even'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='image_des',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='titre',
        ),
        migrations.AddField(
            model_name='activite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='activite',
            name='motivation',
            field=models.TextField(blank=True, null=True, verbose_name='Motivation'),
        ),
        migrations.AddField(
            model_name='activite',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone'),
        ),
    ]
