# Generated by Django 5.0.2 on 2024-08-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_mentor_mentore_delete_mailpersonalise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='modified',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mentore',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mentore',
            name='modified',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
