# Generated by Django 5.0.2 on 2024-03-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_alter_profiles_mentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='profile_scolaire',
            new_name='profile',
        ),
    ]
