# Generated by Django 5.0.2 on 2025-05-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_adession_competence_adession_nom_complet'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='comment_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='comment_views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
