# Generated by Django 5.0.2 on 2024-03-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_profiles_commune_profiles_domaine_profiles_niveau_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='Etablissement',
            new_name='etablissement',
        ),
    ]
