# Generated by Django 5.0.2 on 2024-06-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_adession_remove_activite_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre'),
        ),
    ]
