# Generated by Django 5.0.2 on 2024-08-26 14:03

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_bourse_opportinute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='titre',
            field=models.CharField(default='Bourse et opportunité', max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='bourse_opportinute',
            name='libelle',
            field=models.CharField(default='Bourse et opportunité', max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='mailspersonnalisee',
            name='message',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
