# Generated by Django 5.0.2 on 2025-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_alter_forumcomment_comment_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Even_Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateField(auto_created=True, auto_now_add=True, null=True)),
                ('created', models.DateField(auto_created=True, auto_now_add=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Prenom')),
                ('civilite', models.CharField(blank=True, choices=[('M.', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle'), ('Dr', 'Docteur'), ('Pr', 'Professeur'), ('Me', 'Maître'), ('Autre', 'Autre')], max_length=10, null=True, verbose_name='Civilité')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone')),
                ('addresse', models.TextField(blank=True, null=True, verbose_name='Compétence')),
                ('ville', models.TextField(blank=True, null=True, verbose_name='Ville')),
                ('pays', models.TextField(blank=True, null=True, verbose_name='Pays')),
                ('societe', models.TextField(blank=True, null=True, verbose_name='Société')),
                ('fonction_poste', models.TextField(blank=True, null=True, verbose_name='Fonction /Poste')),
                ('email_pro', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email professionel')),
            ],
        ),
    ]
