# Generated by Django 5.0.2 on 2024-03-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_rename_etablissement_profiles_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
