# Generated by Django 5.0.2 on 2025-05-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0008_even_souscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='even_souscription',
            name='civilite',
            field=models.CharField(blank=True, choices=[('M.', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], max_length=10, null=True, verbose_name='Civilité'),
        ),
    ]
