# Generated by Django 5.0.2 on 2024-03-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0008_alter_profiles_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typementorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateField(auto_created=True, auto_now_add=True, null=True)),
                ('created', models.DateField(auto_created=True, auto_now_add=True, null=True)),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
