# Generated by Django 5.0.2 on 2024-09-12 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0008_alter_activite_titre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteMentorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateField(auto_created=True, auto_now_add=True, null=True)),
                ('created', models.DateField(auto_created=True, auto_now_add=True, null=True)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='images_activites/', verbose_name='Image')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('etat', models.CharField(blank=True, choices=[('en_instance', 'en instance'), ('en_cours', 'en cours'), ('cloture', 'cloturé'), ('annuler', 'annulé')], default='en_instance', max_length=32, null=True)),
                ('mentorat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentors.mentorat')),
            ],
        ),
    ]
