# Generated by Django 5.0.2 on 2025-05-12 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0009_alter_even_souscription_civilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='even_souscription',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentors.evenement'),
        ),
    ]
