# Generated by Django 5.0.2 on 2024-09-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0009_activitementorat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='objectif',
            new_name='confirm_experience_mentor',
        ),
        migrations.AddField(
            model_name='activitementorat',
            name='is_commun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profiles',
            name='confirm_experience_mentore',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='confirm_formation_mentore',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='confirm_mentore',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='objectif_terme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='poste_mentor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='profile_mentorat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='secteur_mentor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitementorat',
            name='etat',
            field=models.CharField(blank=True, choices=[('en_instance', 'En instance'), ('en_cours', 'En cours'), ('cloture', 'Cloturé'), ('annuler', 'Annulé')], default='en_instance', max_length=32, null=True),
        ),
    ]
