# Generated by Django 5.0.2 on 2024-09-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0009_activitementorat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitementorat',
            name='etat',
            field=models.CharField(blank=True, choices=[('en_instance', 'En instance'), ('en_cours', 'En cours'), ('cloture', 'Cloturé'), ('annuler', 'Annulé')], default='en_instance', max_length=32, null=True),
        ),
    ]
