# Generated by Django 5.0.2 on 2024-03-05 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0010_niveau_formation_alter_profiles_type_mentorat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentors.niveau_formation'),
        ),
    ]
