# Generated by Django 5.0.2 on 2025-12-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0010_even_souscription_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osermag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='subtitle')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='mag/', verbose_name='mag')),
                ('isvedette', models.BooleanField()),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('modified', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
