# Generated by Django 5.0.2 on 2024-09-30 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0010_alter_activitementorat_etat'),
        ('mentors', '0010_rename_objectif_profiles_confirm_experience_mentor_and_more'),
    ]

    operations = [
    ]
