# Generated by Django 5.0.2 on 2024-09-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0010_rename_objectif_profiles_confirm_experience_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='objectif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
