# Generated by Django 5.0.2 on 2024-10-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0011_merge_20240930_2223'),
        ('mentors', '0011_profiles_objectif'),
    ]

    operations = [
    ]
