# Generated by Django 5.0.2 on 2026-08-16 19:15

import mentors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0011_osermag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitementorat',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images_activites/', validators=[mentors.validators.validate_document_extension, mentors.validators.validate_document_size], verbose_name='Fichier joint'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[mentors.validators.validate_image_extension, mentors.validators.validate_image_size], verbose_name='Image illustrative'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='forum_img/', validators=[mentors.validators.validate_image_extension, mentors.validators.validate_image_size], verbose_name='Image illustrative'),
        ),
        migrations.AlterField(
            model_name='osermag',
            name='isvedette',
            field=models.BooleanField(verbose_name='est une vedette'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='profile/', validators=[mentors.validators.validate_image_extension, mentors.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='ressources',
            name='ressource',
            field=models.FileField(blank=True, null=True, upload_to='Fichiers/', validators=[mentors.validators.validate_document_extension, mentors.validators.validate_document_size]),
        ),
    ]
