# Generated by Django 5.0.2 on 2024-03-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0013_ressources_arriere_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressources',
            old_name='fichier_pdf',
            new_name='ressource',
        ),
        migrations.RemoveField(
            model_name='ressources',
            name='arriere_plan',
        ),
        migrations.RemoveField(
            model_name='ressources',
            name='video',
        ),
    ]
