# Generated by Django 5.0.2 on 2024-03-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0014_rename_fichier_pdf_ressources_ressource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='date_even',
            field=models.DateField(blank=True, null=True),
        ),
    ]
