# Generated by Django 5.0.2 on 2024-03-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0018_forum_initiateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('valeur', models.TextField(blank=True, null=True)),
                ('presentation_video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('nom_site', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SitesPramettre',
        ),
    ]
