# Generated by Django 5.0.2 on 2024-03-25 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0020_valeur_remove_presentation_valeur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='modified',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='slideimage',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='slideimage',
            name='modified',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='valeur',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='valeur',
            name='modified',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('modified', models.DateField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
