# Generated by Django 5.0.2 on 2024-03-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0022_remove_inbox_owner_remove_inbox_user_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagement',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenu'),
        ),
    ]
