# Generated by Django 5.0.2 on 2024-03-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0023_alter_messagement_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(blank=True, null=True)),
                ('Contenu', models.TextField(blank=True, null=True)),
                ('Visuel', models.FileField(blank=True, null=True, upload_to='images/')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('modified', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
