# Generated by Django 5.0.2 on 2024-03-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0025_alter_projets_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projets',
            old_name='Contenu',
            new_name='contenu',
        ),
    ]
