# Generated by Django 5.0.2 on 2024-03-29 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0026_rename_contenu_projets_contenu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='ojectif',
            new_name='objectif',
        ),
        migrations.AddField(
            model_name='profiles',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='total_time_on_platform',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='libelle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Libelle'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='forum_img/', verbose_name='Image illustrative'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Qui nous sommes'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='mission',
            field=models.TextField(blank=True, null=True, verbose_name='Notre mission'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='vision',
            field=models.TextField(blank=True, null=True, verbose_name='Notre vision'),
        ),
    ]
