# Generated by Django 5.0.2 on 2024-04-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0028_cannaux_communication_cannaux_connaissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='attente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
