# Generated by Django 5.0.2 on 2024-04-05 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0029_profiles_attente'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='cannaux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentors.cannaux_communication'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='connaissance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentors.cannaux_connaissance'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='frequesce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentors.frequence_echange'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='ojectif_academique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentors.objectif_accademique'),
        ),
    ]
