# Generated by Django 5.0.2 on 2024-04-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0030_profiles_cannaux_profiles_connaissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='village',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
