# Generated by Django 5.0.2 on 2024-04-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0031_profiles_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('la_question', models.CharField(blank=True, max_length=200, null=True)),
                ('la_reponse', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('modified', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parteanire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('contenue', models.TextField(blank=True, null=True)),
                ('patenaire_image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('modified', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
