# Generated by Django 5.0.2 on 2024-04-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0032_faq_parteanire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parteanire',
            new_name='Partenaire',
        ),
    ]
