# Generated by Django 5.0.2 on 2024-04-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0033_rename_parteanire_partenaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='libelle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
