# Generated by Django 5.0.2 on 2024-04-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0034_alter_etablissement_libelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='NexletterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.EmailField(blank=True, max_length=254, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('modified', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
