# Generated by Django 5.0.2 on 2024-04-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0035_nexletteremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeur',
            name='titre',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nexletteremail',
            name='useremail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
