# Generated by Django 5.0.2 on 2024-04-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0036_valeur_titre_alter_nexletteremail_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeur',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
